# Generated by Django 2.0.4 on 2018-04-14 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_share', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=30, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.IntegerField(verbose_name='Edicao'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.CharField(max_length=4, verbose_name='Ano'),
        ),
    ]
